"""Memento package."""

from .audio import (
    AudioFrame,
    CaptureHealthReport,
    CaptureHealthSnapshot,
    EnergyVAD,
    InputDeviceInfo,
    MicrophoneConfig,
    OpenAIWhisperBackend,
    RealTimeMicrophone,
    SegmentTranscription,
    SoundDeviceInput,
    SpeechSegment,
    StreamingSpeechSegmenter,
    TranscribedWord,
    VoiceActivityConfig,
    VoiceActivityDecision,
    WavAudio,
    WhisperBackendResult,
    WhisperConfig,
    WhisperTranscriber,
    WhisperTranscriptionPipeline,
    is_cuda_runtime_error,
    is_missing_ffmpeg_error,
    list_input_devices,
    torch_cuda_available,
    load_wav_bytes,
    speech_segment_from_wav_bytes,
    write_wav_file,
)
from .todo import ProjectScope, build_default_scope

__all__ = [
    "AudioFrame",
    "CaptureHealthReport",
    "CaptureHealthSnapshot",
    "EnergyVAD",
    "InputDeviceInfo",
    "MicrophoneConfig",
    "OpenAIWhisperBackend",
    "ProjectScope",
    "RealTimeMicrophone",
    "SegmentTranscription",
    "SoundDeviceInput",
    "SpeechSegment",
    "StreamingSpeechSegmenter",
    "TranscribedWord",
    "VoiceActivityConfig",
    "VoiceActivityDecision",
    "WavAudio",
    "WhisperBackendResult",
    "WhisperConfig",
    "WhisperTranscriber",
    "WhisperTranscriptionPipeline",
    "is_cuda_runtime_error",
    "is_missing_ffmpeg_error",
    "list_input_devices",
    "torch_cuda_available",
    "build_default_scope",
    "load_wav_bytes",
    "speech_segment_from_wav_bytes",
    "write_wav_file",
]
