"""Memento package."""

from importlib import import_module

from .audio import (
    AudioFrame,
    AudioOutputDevice,
    CaptureHealthReport,
    CaptureHealthSnapshot,
    DEFAULT_VOXTRAL_MODEL_NAME,
    DecodedAudio,
    EnergyVAD,
    InputDeviceInfo,
    MicrophoneConfig,
    OpenAIWhisperBackend,
    PlaybackResult,
    RealTimeMicrophone,
    SegmentTranscription,
    SoundDeviceOutput,
    SoundDeviceInput,
    SpeakerConfig,
    SpeakerPlayer,
    SpeechSynthesizer,
    SpeechSegment,
    StreamingSpeechSegmenter,
    SUPPORTED_TTS_RESPONSE_FORMATS,
    SynthesizedSpeech,
    TextToSpeechBackend,
    TextToSpeechBackendResult,
    TextToSpeechConfig,
    TranscribedWord,
    VoiceExperienceMetrics,
    VoiceExperienceTargets,
    VoiceActivityConfig,
    VoiceActivityDecision,
    VoiceResponsePipeline,
    VoiceResponseResult,
    VoxtralTTSBackend,
    WavAudio,
    WhisperBackendResult,
    WhisperConfig,
    WhisperTranscriber,
    WhisperTranscriptionPipeline,
    is_cuda_runtime_error,
    is_missing_ffmpeg_error,
    list_input_devices,
    torch_cuda_available,
    decode_audio_bytes,
    load_wav_bytes,
    speech_segment_from_wav_bytes,
    write_wav_file,
)
from .memory import (
    AffectiveState,
    GraphStore,
    InMemoryChromaCollection,
    InMemoryGraphStore,
    LlamaIndexSemanticIndex,
    MemoryContextHit,
    MemoryDocument,
    MemoryDocumentProjector,
    MemoryEpisode,
    MemoryGraphSchema,
    MemoryNode,
    MemoryRecall,
    MemoryRelation,
    MemorySyncEngine,
    MemorySyncReport,
    PatientMemorySnapshot,
    PatientProfile,
    PersonProfile,
    PersonalMemoryGraph,
    PlaceProfile,
    RoutineProfile,
    SemanticMemoryIndex,
    SemanticIndex,
    SemanticSearchHit,
    build_memory_graph,
    default_memory_schema,
)

__all__ = [
    "AudioFrame",
    "AudioOutputDevice",
    "ChromaSemanticIndex",
    "CaptureHealthReport",
    "CaptureHealthSnapshot",
    "DEFAULT_VOXTRAL_MODEL_NAME",
    "DecodedAudio",
    "EnergyVAD",
    "GraphStore",
    "InMemoryChromaCollection",
    "InMemoryGraphStore",
    "InputDeviceInfo",
    "LlamaIndexSemanticIndex",
    "MemoryContextHit",
    "MemoryDocument",
    "MemoryDocumentProjector",
    "MemoryEpisode",
    "MemoryGraphSchema",
    "MemoryNode",
    "MemoryRecall",
    "MemoryRelation",
    "MemorySyncEngine",
    "MemorySyncReport",
    "MicrophoneConfig",
    "Neo4jGraphStore",
    "OpenAIWhisperBackend",
    "PlaybackResult",
    "PatientMemorySnapshot",
    "PatientProfile",
    "PersonProfile",
    "PersonalMemoryGraph",
    "PlaceProfile",
    "RealTimeMicrophone",
    "RoutineProfile",
    "SegmentTranscription",
    "SemanticMemoryIndex",
    "SemanticIndex",
    "SemanticSearchHit",
    "SoundDeviceOutput",
    "SoundDeviceInput",
    "SpeakerConfig",
    "SpeakerPlayer",
    "SpeechSynthesizer",
    "SpeechSegment",
    "StreamingSpeechSegmenter",
    "SUPPORTED_TTS_RESPONSE_FORMATS",
    "SynthesizedSpeech",
    "TextToSpeechBackend",
    "TextToSpeechBackendResult",
    "TextToSpeechConfig",
    "TranscribedWord",
    "VoiceExperienceMetrics",
    "VoiceExperienceTargets",
    "VoiceActivityConfig",
    "VoiceActivityDecision",
    "VoiceResponsePipeline",
    "VoiceResponseResult",
    "VoxtralTTSBackend",
    "WavAudio",
    "WhisperBackendResult",
    "WhisperConfig",
    "WhisperTranscriber",
    "WhisperTranscriptionPipeline",
    "AffectiveState",
    "is_cuda_runtime_error",
    "is_missing_ffmpeg_error",
    "list_input_devices",
    "torch_cuda_available",
    "build_memory_graph",
    "decode_audio_bytes",
    "default_memory_schema",
    "load_wav_bytes",
    "speech_segment_from_wav_bytes",
    "write_wav_file",
]


def __getattr__(name: str):
    if name not in {"ChromaSemanticIndex", "Neo4jGraphStore"}:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    module = import_module(".memory", __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value
