"""Memento package."""

from .audio import (
    AudioFrame,
    CaptureHealthReport,
    CaptureHealthSnapshot,
    EnergyVAD,
    FasterWhisperBackend,
    MicrophoneConfig,
    RealTimeMicrophone,
    SegmentTranscription,
    SpeechSegment,
    TranscribedWord,
    VoiceActivityConfig,
    VoiceActivityDecision,
    WavAudio,
    WhisperBackendResult,
    WhisperConfig,
    WhisperTranscriber,
    WhisperTranscriptionPipeline,
    load_wav_bytes,
    speech_segment_from_wav_bytes,
    write_wav_file,
)
from .todo import ProjectScope, build_default_scope

__all__ = [
    "AudioFrame",
    "CaptureHealthReport",
    "CaptureHealthSnapshot",
    "EnergyVAD",
    "FasterWhisperBackend",
    "MicrophoneConfig",
    "ProjectScope",
    "RealTimeMicrophone",
    "SegmentTranscription",
    "SpeechSegment",
    "TranscribedWord",
    "VoiceActivityConfig",
    "VoiceActivityDecision",
    "WavAudio",
    "WhisperBackendResult",
    "WhisperConfig",
    "WhisperTranscriber",
    "WhisperTranscriptionPipeline",
    "build_default_scope",
    "load_wav_bytes",
    "speech_segment_from_wav_bytes",
    "write_wav_file",
]
